### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'fiConf'

### ISSUE THREAD

**Issue by abhishektyaagi** [DependableSystemsLab/TensorFI#50]
While specifying the path for config file, I am getting this error:

Traceback (most recent call last):
  File "train/test.py", line 516, in <module>
    test_from_rgb_detection(FLAGS.output+'.pickle', FLAGS.output)
  File "train/test.py", line 298, in test_from_rgb_detection
    batch_one_hot_to_feed, batch_size=batch_size)
  File "train/test.py", line 172, in inference
    fi = ti.TensorFI(sess,fiConf = "/u/atyagi2/frustum-pointnets/confFiles/default.yaml", name = "FrustumPointNet", logLevel = 50,disableInjections = False)
TypeError: __init__() got an unexpected keyword argument 'fiConf'

Is 'fiConfi' the right keyword or I am doing something wrong?

**Comment by nniranjhana** [comment]
Hi @abhishek-t-naive the right keyword argument is `configFileName`, you can also check this in the source file where the constructor of the tensorFI injection function is [defined](https://github.com/DependableSystemsLab/TensorFI/blob/2f5a8d5d0846581f82ead5420d984558399fd6f0/TensorFI/tensorFI.py#L165):

> configFileName = "confFiles/default.yaml",	# Config file for reading fault configuration
